name: Clone Banco Generoso

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"

permissions:
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: Fit-Iuri/github-actions-training
          ref: refs/heads/whitelabel/CachorroBank
          token: ${{ secrets.API_TOKEN_GITHUB || github.token }}
          fetch-depth: 0