name: Clone Private Repository Workflow

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: Fit-Iuri/github-actions-training
          ref: refs/heads/whitelabel/CachorroBank
          token: ${{ secrets.API_TOKEN_GITHUB_2 || github.token }}
          fetch-depth: 0
